project:
  type: website
  output-dir: docs
  resources:
    - images/icons/*.svg

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

    tools:
      - text: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/teo4shore"
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: "https://www.linkedin.com/in/matteo-riva-b91308198/"
      - text: "{{< iconify fa6-brands google-scholar >}}"
        href: "https://scholar.google.com/citations?user=EEQo6Y8AAAAJ&hl=en"
      - text: "{{< iconify fa6-brands orcid >}}"
        href: "https://orcid.org/0000-0001-9759-3911"
      - text: "{{< iconify fa6-solid envelope >}}"
        href: "mailto:rivam@ethz.ch"


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



