project:
  type: website
  output-dir: docs

website:
  title: "teo4shore.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://scholar.google.com/citations?user=EEQo6Y8AAAAJ&hl=en
        text: "![](images/icons/google-scholar.svg){height=1.4rem}"
    tools: 
      - icon: github
        href: https://github.com/teo4shore
      - icon: linkedin
        href: https://www.linkedin.com/in/matteo-riva-b91308198/
      - icon: orcid
        href: https://orcid.org/0000-0001-9759-3911
      - text: Scholar
        href: https://scholar.google.com/citations?user=EEQo6Y8AAAAJ&hl=en       
      - icon: envelope
        href: mailto:rivam@ethz.ch

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



