project:
  type: website
  output-dir: docs

website:
  title: "teo4shore.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools: 
      - icon: github
        href: https://github.com/teo4shore
      - icon: linkedin
        href: https://www.linkedin.com/in/matteo-riva-b91308198/
      - icon: envelope
        href: mailto:rivam@ethz.ch

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



